PIC24H Project Template: Main Program
Main Program
This module contains the main function.
Files
file main.c
Main Program.
Functions
int main (void)
Detailed Description
This module contains the main function.
Function Documentation
int main (void)
Definition at line 35 of file main.c.
References delayMs(), ENABLED, init(), lcd_clear(), lcd_conf_display(), lcd_display_char(), lcd_init(), LED1(), OFF, ON, spi_init(), TOGGLE, and TRUE.
 {
     // Initialize hardware (with PLL enabled)
     init (TRUE);
     // Configure LED1
     LED1 (ENABLED);
     LED1 (OFF);
     spi_init ();
     lcd_init ();
     // Turn on display, but disable cursor and position marker
     lcd_conf_display (ON, OFF, OFF);
     uint8_t u8test = 0;
     while (1)
     {
         // Clear Display first
         lcd_clear ();
         uint8_t u8copy = u8test, u8len = 0, au8nums[5];
         int8_t i8count;
         // Write decimal digits of number to array
         while (u8copy != 0)
         {
             au8nums[u8len++] = u8copy % 10;
             u8copy /= 10;
         }
         // Print out decimals
         for (i8count = u8len-1; i8count > -1; i8count--)
             lcd_display_char (48 + au8nums[i8count]);
         // Handle 0 seperately
         if (u8len == 0)
             lcd_display_char (48);
         lcd_display_char (':');
         lcd_display_char (' ');
         // Print out corresponding character
         lcd_display_char (u8test);
         u8test++;
         // Toggle LED1 every second
         LED1 (TOGGLE);
         delayMs (1000);
     }
     return 0;
 }