PIC24H Project Template: PIC Utility Functions
PIC Utility Functions
This module contains some helpful functions for working with PIC Microcontrollers, like accessing LEDs and Buttons.
Files
file utils.h
PIC Utility functions.
file utils.c
Implements utility functions.
Macros
#define OFF 0
#define ON 1
#define DISABLED 2
#define ENABLED 3
#define TOGGLE 4
Functions
void delayMs (uint16_t u16delay)
Simple Delay Function.
void LED (volatile uint16_t *u16ledtris, volatile uint16_t *u16ledlat, uint8_t u8led, uint8_t u8action)
LED Configuration Function.
uint8_t button_is_pressed (volatile uint16_t *u16register, uint8_t u8port)
Wrapper fuction for getting the state of a button.
Detailed Description
This module contains some helpful functions for working with PIC Microcontrollers, like accessing LEDs and Buttons.
Macro Definition Documentation
#define DISABLED 2
Definition at line 41 of file utils.h.
Referenced by LED().
#define ENABLED 3
Definition at line 42 of file utils.h.
Referenced by LED(), and main().
#define OFF 0
Definition at line 39 of file utils.h.
Referenced by LED(), and main().
#define ON 1
Definition at line 40 of file utils.h.
Referenced by LED().
#define TOGGLE 4
Definition at line 43 of file utils.h.
Referenced by LED(), and main().
Function Documentation
uint8_t button_is_pressed (volatile uint16_t * u16register, uint8_t u8port)
Wrapper fuction for getting the state of a button.
Parameters
u16register The corresponding PORT Register
u8port The bit offset in the Register (Port number)
Definition at line 61 of file utils.c.
References delayMs().
 {
     // Wait for the Button to reach its final state
     delayMs (1);
     return ! (*u16register & (1<<u8port));
 }
void delayMs (uint16_t u16delay)
Simple Delay Function.
Creates an approximately one millisecond delay.
Parameters
u16delay Number of Milliseconds to wait
Definition at line 31 of file utils.c.
Referenced by button_is_pressed(), lcd_cmd(), lcd_display_char(), and main().
 {
     uint16_t u16i;
     for (; u16delay > 0; u16delay--)
         for (u16i = 0; u16i <= 5500; u16i++);
 }
void LED (volatile uint16_t * u16ledtris, volatile uint16_t * u16ledlat, uint8_t u8led, uint8_t u8action)
LED Configuration Function.
Can enable, disable, switch on/off/toggle a LED
Parameters
u16ledtris The corresponding TRIS Register of the LED
u16ledlat The corresponding LAT Register of the LED
u8led The Bit offset in the Registers (Port number)
u8action The action to perform (e.g. ENABLE, OFF, ON, TOGGLE, etc)
Definition at line 38 of file utils.c.
References DISABLED, ENABLED, OFF, ON, and TOGGLE.
Referenced by main().
 {
     switch ( u8action )
     {
         case ON:
             *u16ledlat |= (1 << u8led);
             break;
         case OFF:
             *u16ledlat &= ~(1 << u8led);
             break;
         case TOGGLE:
             *u16ledlat ^= (1 << u8led);
             break;
         case ENABLED:
             *u16ledtris &= ~(1 << u8led);
             break;
         case DISABLED:
         default:
             *u16ledtris |= (1 << u8led);
             break;
     }
 }