PIC24H Project Template: LCD Helper Functions
LCD Helper Functions
This module contains functions to handle output and sending data to the LCD display.
Files
file lcd.h
LCD helper functions.
file lcd.c
Implements LCD functions.
Macros
#define LCD_STAT SPI1STAT
#define LCD_CON1 SPI1CON1
#define LCD_STATbits SPI1STATbits
#define LCD_CON1bits SPI1CON1bits
#define LCD_CON2bits SPI1CON2bits
#define LCD_BUF SPI1BUF
#define RS LATAbits.LATA3
#define CSB LATAbits.LATA4
#define SS LATBbits.LATB7
Functions
void lcd_cmd (uint8_t u8cmd)
SPI Function to send a command to the lcd display.
void lcd_display_char (c8_t c8character)
SPI Function to display characters on the display.
void lcd_display_string (c8_t *pac8string)
Displays a string on the display.
void lcd_display_long_string (c8_t *pac8string, uint16_t u16delay)
Displays a longer string by splitting it at linebreaks and displaying the lines seperately.
void lcd_display_number (int16_t i16num)
Displays a given number on the LCD in decimal and hexadecimal format.
void lcd_init (void)
Function to initialize the display.
void lcd_clear (void)
Clears the LCD display.
void lcd_conf_display (bool b8display, bool b8cursor, bool b8position)
Configures the LCD display.
void lcd_set_cursor (uint8_t u8line, uint8_t u8col)
Sets the display cursor at a specific position.
void spi_init (void)
Initializes SPI1 to work properly.
Detailed Description
This module contains functions to handle output and sending data to the LCD display.
Macro Definition Documentation
#define CSB LATAbits.LATA4
Definition at line 44 of file lcd.h.
Referenced by lcd_cmd(), lcd_display_char(), and spi_init().
#define LCD_BUF SPI1BUF
Definition at line 42 of file lcd.h.
Referenced by lcd_cmd(), and lcd_display_char().
#define LCD_CON1 SPI1CON1
Definition at line 38 of file lcd.h.
#define LCD_CON1bits SPI1CON1bits
Definition at line 40 of file lcd.h.
Referenced by spi_init().
#define LCD_CON2bits SPI1CON2bits
Definition at line 41 of file lcd.h.
Referenced by spi_init().
#define LCD_STAT SPI1STAT
Definition at line 37 of file lcd.h.
#define LCD_STATbits SPI1STATbits
Definition at line 39 of file lcd.h.
Referenced by lcd_cmd(), lcd_display_char(), and spi_init().
#define RS LATAbits.LATA3
Definition at line 43 of file lcd.h.
Referenced by lcd_cmd(), and lcd_display_char().
#define SS LATBbits.LATB7
Definition at line 45 of file lcd.h.
Function Documentation
void lcd_clear (void)
Clears the LCD display.
Sends the commands needed to clear the LCD display.
Definition at line 200 of file lcd.c.
References delayMs(), and lcd_cmd().
Referenced by lcd_display_long_string().
 {
     lcd_cmd (0x01); // Clear Display
     delayMs (5);
     lcd_cmd (0x39); // Function Set
     delayMs (5);
     lcd_cmd (0x06); // Cursor auto-increment
     delayMs (5);
 }
void lcd_cmd (uint8_t u8cmd)
SPI Function to send a command to the lcd display.
Sends a HEX command to the Display over SPI
Parameters
u8cmd The Command to be sent (HEX)
Definition at line 35 of file lcd.c.
References CSB, LCD_BUF, LCD_STATbits, and RS.
Referenced by lcd_clear(), lcd_conf_display(), lcd_init(), and lcd_set_cursor().
 {
     RS = 0;               // Command mode
     CSB = 0;              // Select display
     LCD_BUF;              // Read Buffer -> Clear RBF bit
     LCD_BUF = u8cmd;      // Write command bits
     LCD_BUF;              // Read Buffer -> Clear RBF bit
     while (LCD_STATbits.SPITBF); // wait until all bits are sent
     uint16_t i;
     for (i = 0; i < 150; i++);  // Create a small delay
     CSB = 1;                    // Unselect display
 }
void lcd_conf_display (bool b8display, bool b8cursor, bool b8position)
Configures the LCD display.
Can configure the display:
Turn display on/off
Turn displaying of cursor on/off
Turn displaying of cursor position on/off
Parameters
b8display If the display should be on/off
b8cursor If the displaying of the cursor should be on/off
b8position If the displaying of the cursor position should be on/off
Definition at line 157 of file lcd.c.
References delayMs(), and lcd_cmd().
Referenced by main().
 {
     lcd_cmd (0x08 | (b8display << 2) | (b8cursor << 1) | b8position);
     delayMs (1);
 }
void lcd_display_char (c8_t c8character)
SPI Function to display characters on the display.
Generally it sends data to the LCD Display.
But most times this will be a character.
Parameters
c8character The Character to be displayed
Definition at line 49 of file lcd.c.
References CSB, LCD_BUF, LCD_STATbits, and RS.
Referenced by lcd_display_string().
 {
     RS = 1;               // Beginning of Data mode
     CSB = 0;              // Select display
     LCD_BUF;              // Read Buffer -> Clear RBF bit
     LCD_BUF = c8character;      // Write command bits
     LCD_BUF;              // Read Buffer -> Clear RBF bit
     while (LCD_STATbits.SPITBF); // wait until all bits are sent
     uint16_t i;
     for (i = 0; i < 150; i++); // Create a small delay
     RS = 0;               // Quit data mode
     CSB = 1;              // Unselect display
 }
void lcd_display_long_string (c8_t * pac8string, uint16_t u16delay)
Displays a longer string by splitting it at linebreaks and displaying the lines seperately.
The string is scrolling upwards every u16delay milliseconds.
It is also possible to use two linebreaks in sequence in the string to create an empty line on the display.
Parameters
pac8string A pointer to the beginning of the string.
u16delay The delay to be used between displaying the next two lines in milliseconds.
Definition at line 92 of file lcd.c.
References delayMs(), FALSE, lcd_clear(), lcd_display_string(), lcd_set_cursor(), and TRUE.
Referenced by main().
 {
     // Used later to remember the passed string.
     static c8_t *pc8char = NULL;
     // Array to hold our single lines
     static c8_t *ac8buf[30];
     // Line count
     static uint8_t u8count = 0;
     // Array index
     uint8_t u8index = 0;
     // If the string hasn't already been parsed
     if (pc8char == NULL || pc8char != pac8string)
     {
         pc8char = pac8string;
         // Split string by using linebreaks as delimiters
         pc8char = strtok (pac8string, "\n");
         // While there are still linebreaks in the string
         while (pc8char != NULL)
         {
             // Store the line in the array
             ac8buf[u8index++] = pc8char;
             // Get next line in string
             pc8char = strtok (NULL, "\n");
             // Increment Line count
             u8count++;
         }
         // Remember this string
         pc8char = pac8string;
     }
     u8index = 0;
     // to handle two \n's in sequence: Insert a newline
     bool b8skipline = FALSE;
     // Iterate over the lines
     while (u8index < u8count)
     {
         lcd_clear ();
         // If the line does not have to be clear because of a second newline
         if (!b8skipline)
             // Display the line
             lcd_display_string (ac8buf[u8index]);
         // Go to the second line
         lcd_set_cursor (1, 0);
         // If the previous line didn't have to be clear
         if (!b8skipline)
             // Look if the line has a second \n
             if (*(ac8buf[u8index+1]-1) == '\n')
                 // Then skip this line and next time, put this line in the second line
                 b8skipline = TRUE;
             else
                 // Otherwise display the line
                 lcd_display_string (ac8buf[++u8index]);
         else
         {
             // Otherwise display the line in the second line instead of the first line.
             lcd_display_string (ac8buf[++u8index]);
             // Finally done.
             b8skipline = FALSE;
         }
         delayMs (u16delay);
     }
 }
void lcd_display_number (int16_t i16num)
Displays a given number on the LCD in decimal and hexadecimal format.
Parameters
i16num The number
Definition at line 85 of file lcd.c.
References lcd_display_string().
 {
     c8_t ac8buf[17];
     sprintf (ac8buf, "%-6d %4x", i16num, i16num);
     lcd_display_string (ac8buf);
 }
void lcd_display_string (c8_t * pac8string)
Displays a string on the display.
Takes an array of characters and simply sends them all to the display.
Parameters
pac8string A pointer to the beginning of a string
Definition at line 67 of file lcd.c.
References lcd_display_char(), and lcd_set_cursor().
Referenced by lcd_display_long_string(), and lcd_display_number().
 {
     // Simply write each character
     while (*pac8string)
     {
         // Hack to add support for linebreak in strings :)
         if (*pac8string == '\n')
         {
             // Jump to the second line
             lcd_set_cursor (1,0);
             pac8string++;
         }
         else
             // Otherwise display the character
             lcd_display_char (*pac8string++);
     }
 }
void lcd_init (void)
Function to initialize the display.
Configures the Ports and SPI and sends the Initialization commands to the display.
Definition at line 216 of file lcd.c.
References delayMs(), and lcd_cmd().
Referenced by main().
 {
     // Display Initialisation Commands
     lcd_cmd (0x39); // Function Set
     delayMs (5);
     lcd_cmd (0x14); // Bias Set
     delayMs (5);
     lcd_cmd (0x55); // Power Control
     delayMs (500);
     lcd_cmd (0x6D); // Follower Control
     delayMs (5);
     lcd_cmd (0x78); // Contrast Set
     delayMs (5);
     lcd_cmd (0x38); // Instruction Table 0
     delayMs (5);
     lcd_cmd (0x0F); // Display ON, Curson on, blink
     delayMs (5);
     lcd_cmd (0x01); // Clear Display
     delayMs (5);
     lcd_cmd (0x06); // Cursor auto-increment
     delayMs (5);
 }
void lcd_set_cursor (uint8_t u8line, uint8_t u8col)
Sets the display cursor at a specific position.
Parameters
u8line The line to set the cursor to
u8col The column to set the cursor to
Definition at line 210 of file lcd.c.
References delayMs(), and lcd_cmd().
Referenced by lcd_display_long_string(), and lcd_display_string().
 {
     lcd_cmd (0x80 | (u8line << 6) | u8col);
     delayMs (5);
 }
void spi_init (void)
Initializes SPI1 to work properly.
Configures the Registers relevant to SPI so that it works correctly.
Definition at line 163 of file lcd.c.
References CSB, delayMs(), LCD_CON1bits, LCD_CON2bits, and LCD_STATbits.
Referenced by main().
 {
     RPOR3bits.RP7R = 9; // RP7 -> SS1
     RPOR2bits.RP4R = 8; // RP4 -> SCK1
     RPOR2bits.RP5R = 7; // RP5 -> SDO1
     RPINR20bits.SDI1R = 6; // RP6 -> SDI1
     TRISBbits.TRISB4 = 0; // SCK -> Output
     TRISBbits.TRISB5 = 0; // SDO -> Output
     TRISBbits.TRISB6 = 1; // SDI -> Input
     TRISBbits.TRISB7 = 0; // SS -> Output
     TRISAbits.TRISA3 = 0; // RS  -> Output
     TRISAbits.TRISA4 = 0; // CSB -> Output
     CSB = 1; // Unselect Display
     IFS0bits.SPI1IF = 0; // Clear Interrupt Flag
     IFS0bits.SPI1EIF = 0; // Disable Interrupts
     LCD_CON1bits.CKP = 1;    // Idle state for clock is a high level
     LCD_CON1bits.CKE = 0;    // Data out on idle to active edge
     LCD_CON1bits.MODE16 = 0; // 8-bit data transfer mode
     LCD_CON1bits.MSTEN = 1;  // Enable Master mode
     LCD_CON1bits.PPRE = 1;   // Set Primary Pre-scalar for 16:1 ratio
     LCD_CON1bits.SPRE = 1;   // Set Secondary Pre-scalar for 7:1 ratio
     LCD_CON1bits.SMP = 0;    // Sample Input Data at middle of data output time
     LCD_CON1bits.DISSDO = 0; // Enable SDO output
     LCD_CON1bits.DISSCK = 0; // Enable SCK output
     LCD_CON1bits.SSEN = 0;   // Disable SS
     LCD_CON2bits.FRMEN = 0;  // Disable Framed SPI mode
     LCD_STATbits.SPIROV = 0; // Clear Overflow Bit
     LCD_STATbits.SPISIDL = 0;// Continue Operation in Idle mode
     delayMs (50);
     LCD_STATbits.SPIEN = 1;  // Enable SPI module
 }